/**
 * Demo Applicants Generator for Recruiter ATS Kanban Pipeline
 * Provides realistic candidate archetypes populated across pipeline stages
 * when DB is fresh, offline, or viewing demo positions.
 */

export const getDemoApplicantsForJob = (jobId = 'demo-job') => [
  {
    _id: `demo_app_1_${jobId}`,
    job: jobId,
    status: 'applied',
    candidate: {
      _id: 'cand_1',
      name: 'Priya Sharma',
      email: 'priya.sharma@fullstack.dev',
      profile: {
        targetRole: 'Full Stack Engineer',
        location: 'Bengaluru, India (Remote)',
      },
    },
    aiMatchScore: 82,
    recommendation: 'Strong Match',
    matchedSkills: ['React', 'Node.js', 'Express', 'MongoDB'],
    missingSkills: ['Gemini AI', 'Docker'],
    experienceFit: '3+ years full-stack JavaScript experience delivering commercial SaaS web apps.',
    fitSummary: 'Solid full-stack JavaScript foundation with clean coding practices and eager aptitude for AI tooling.',
    resumeUrl: '/uploads/resumes/sample-priya-sharma.pdf',
    appliedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    _id: `demo_app_2_${jobId}`,
    job: jobId,
    status: 'applied',
    candidate: {
      _id: 'cand_2',
      name: 'David Miller',
      email: 'david.miller@frontendcraft.co',
      profile: {
        targetRole: 'Senior Frontend & AI Engineer',
        location: 'Austin, TX (Remote)',
      },
    },
    aiMatchScore: 76,
    recommendation: 'Moderate Match',
    matchedSkills: ['React', 'TypeScript', 'Gemini AI', 'TailwindCSS'],
    missingSkills: ['MongoDB', 'Docker'],
    experienceFit: '3.5 years developing responsive client-side web apps and generative AI streaming UIs.',
    fitSummary: 'Capable UI specialist with practical Gemini generative UI experience. Backend persistence and container workflows need pairing support.',
    resumeUrl: '/uploads/resumes/sample-david-miller.pdf',
    appliedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    _id: `demo_app_3_${jobId}`,
    job: jobId,
    status: 'shortlisted',
    candidate: {
      _id: 'cand_3',
      name: 'Alex Chen',
      email: 'alex.chen@techlead.dev',
      profile: {
        targetRole: 'Staff Software Engineer',
        location: 'San Francisco, CA',
      },
    },
    aiMatchScore: 94,
    recommendation: 'Strong Match',
    matchedSkills: ['React', 'Node.js', 'Express', 'MongoDB', 'Gemini AI', 'Docker'],
    missingSkills: [],
    experienceFit: '5+ years architecting enterprise MERN applications with native LLM orchestration.',
    fitSummary: 'Exceptional technical alignment. Demonstrated production leadership with Gemini API structured outputs, containerization, and high-throughput MongoDB pipelines.',
    resumeUrl: '/uploads/resumes/sample-alex-chen.pdf',
    appliedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    _id: `demo_app_4_${jobId}`,
    job: jobId,
    status: 'interview',
    candidate: {
      _id: 'cand_4',
      name: 'Sarah Jenkins',
      email: 'sarah.j@cloudcore.io',
      profile: {
        targetRole: 'Backend Systems Engineer',
        location: 'Seattle, WA (Hybrid)',
      },
    },
    aiMatchScore: 88,
    recommendation: 'Strong Match',
    matchedSkills: ['Node.js', 'Express', 'MongoDB', 'Docker', 'REST API'],
    missingSkills: ['Gemini AI'],
    experienceFit: '4 years deep backend engineering with microservices, Redis caching, and MongoDB aggregation.',
    fitSummary: 'Strong backend fundamentals and distributed systems depth. Minor ramp-up needed on Gemini SDK inference endpoints.',
    resumeUrl: '/uploads/resumes/sample-sarah-jenkins.pdf',
    appliedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    _id: `demo_app_5_${jobId}`,
    job: jobId,
    status: 'hired',
    candidate: {
      _id: 'cand_5',
      name: 'Elena Rostova',
      email: 'elena.rostova@ai-architects.io',
      profile: {
        targetRole: 'Lead AI Platform Architect',
        location: 'New York, NY',
      },
    },
    aiMatchScore: 96,
    recommendation: 'Strong Match',
    matchedSkills: ['React', 'Node.js', 'Express', 'MongoDB', 'Gemini AI', 'Docker', 'Python'],
    missingSkills: [],
    experienceFit: '6 years building scalable AI-native SaaS platforms with MERN and Google Cloud.',
    fitSummary: 'Outstanding candidate across all dimensions. Impeccable technical depth, system design prowess, and extensive foundation model deployment history.',
    resumeUrl: '/uploads/resumes/sample-elena-rostova.pdf',
    appliedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    _id: `demo_app_6_${jobId}`,
    job: jobId,
    status: 'rejected',
    candidate: {
      _id: 'cand_6',
      name: 'Marcus Vance',
      email: 'marcus.v@opsnet.net',
      profile: {
        targetRole: 'Site Reliability Engineer',
        location: 'Denver, CO',
      },
    },
    aiMatchScore: 44,
    recommendation: 'Low Match',
    matchedSkills: ['Docker', 'AWS', 'Linux'],
    missingSkills: ['React', 'Node.js', 'MongoDB', 'Gemini AI'],
    experienceFit: 'Heavy DevOps and infrastructure background with limited application-level MERN development.',
    fitSummary: 'High cloud and sysadmin capability, but lacking essential frontend and backend MERN application engineering experience.',
    resumeUrl: '/uploads/resumes/sample-marcus-vance.pdf',
    appliedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isDemo: true,
  },
];
